// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1) {
  return window['go']['main']['App']['Exec'](arg1);
}

export function GetInitialList() {
  return window['go']['main']['App']['GetInitialList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
