// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1:string):Promise<void>;

export function GetInitialList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function Search(arg1:string):Promise<Array<string>>;
